spring:
  datasource:
    url: jdbc:h2:mem:teste
    driverClassName: org.h2.Driver
    username: sa
    password:

spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect

# H2
spring.h2:
  console:
    enabled: true
    path: /h2

spring.mvc:
  pathmatch:
    matching-strategy: ant-path-matcher